spring.application.name=api

# 🔹 Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/guia_4
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 🔹 Configuración de Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 🔹 Configuración de JWT (ya la tienes)
jwt.secret=RealMadridCampeondelaChampionsLeague2026HALAMADRID
jwt.expiration=3600000

# ============================================================
# 🔹 NUEVO: Configuración de OAuth2 con Google
# ============================================================
spring.security.oauth2.client.registration.google.client-id=174455031568-4nejml6gdorv0s7gjujq87mue6rivm5s.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=GOCSPX-HOYhh2-pgll1k-1SHmSm1OFUZHG
spring.security.oauth2.client.registration.google.scope=openid,profile,email


# Opcional: URL de proveedor (Spring Boot ya las trae por defecto, pero puedes definirlas explícitamente)
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
